name: Doc PDF Generation

on: push

jobs:
  pdf-generation:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: install apt dependencies
      run: |
        apt-get update
        apt-get install texlive wget -y
        wget https://github.com/jgm/pandoc/releases/download/2.11.0.2/pandoc-2.11.0.2-1-amd64.deb
        dpkg -i pandoc-2.11.0.2-1-amd64.deb
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: install dependencies and generate PDF
      run: |
        npm install -g pandoc-plantuml
        pandoc -s --columns=100 -F pandoc-plantuml -o secure-control-protocol-specification.pdf doc/secure-control-protocol-specification.md
    - uses: actions/upload-artifact@v1
      with:
        name: secure-control-protocol-specification.pdf
        path: secure-control-protocol-specification.pdf