name: Doc PDF Generation

on: push

jobs:
  pdf-generation:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: install dependencies and generate PDF
      run: |
        sudo apt-get install pandoc texlive
        npm install -g pandoc-plantuml
        pandoc -s --columns=100 -F pandoc-plantuml -o secure-control-protocol-specification.pdf doc/secure-control-protocol-specification.md
    - uses: actions/upload-artifact@v1
      with:
        name: secure-control-protocol-specification.pdf
        path: secure-control-protocol-specification.pdf